### PR TITLE
Airflow(#6)

### PR DESCRIPTION
**Pull request by kmouleejunhyuk**
add airflow example dag

### CODE REVIEW

**Comment by kmouleejunhyuk** [comment]
question: Is example case must be reproducable via docker?

**Review by jaehwan-AI — COMMENTED** [review]
1. What is xcom?
2. Can I see the dag you added in today's meeting on the web UI?

**Comment by kmouleejunhyuk** [comment]
> * What is xcom?
> * Can I see the dag you added in today's meeting on the web UI?

xcom is used to transfer task output to another task. but using decorators seems to be much more useful

**Review by jaehwan-AI — APPROVED** [review]
Okay. You put so much effort into it.

**Pull request merged**
